name: ecom
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  connectivity_plus: ^3.0.3
  iconsax: ^0.0.8
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.1.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.4
  firebase_storage: ^12.1.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0
  data_table_2: ^2.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/animations/72462-check-register.json
    - assets/icons/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/products/
    - assets/images/reviews/
    - assets/images/content/user.png

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800