// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPtc64cIM_TUV3kSWzARRU2xHoKxLGi6k',
    appId: '1:91666252486:android:8cd4cf640d4a0acbeecdc7',
    messagingSenderId: '91666252486',
    projectId: 'ecom-4c424',
    storageBucket: 'ecom-4c424.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVpuSShMOwK_fHonFqNnIX-QeVnG0kq4Q',
    appId: '1:91666252486:ios:c15f5776ae3635a6eecdc7',
    messagingSenderId: '91666252486',
    projectId: 'ecom-4c424',
    storageBucket: 'ecom-4c424.appspot.com',
    androidClientId: '91666252486-hccq9d29ejpnsco1emof2p4glafm4tn3.apps.googleusercontent.com',
    iosClientId: '91666252486-7ocfklhrj87d7k88smnjah8uhud9e9ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );

}